name: Norminette Check
on: [push, pull_request]
jobs:
  check_norm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Norminette 42
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
      
      - name: Run Norminette
        run: |
          norminette $(find .h -name "*.c" -o -name "*.h")
      
      - name: Test Compilation (Makefile)
        run: |
          if [ -f "Makefile"]; then
            make
            make clean
            make fclean
            echo " Le Makefile compile et se nettoie correctement !"
          else
            echo "Makefile intouvable !"
            exit 1
          fi
